name: Python Test

on:
  push:
    branches: [ "main" ]  # main分支推送时触发
  pull_request:
    branches: [ "main" ]  # 向main分支提交PR时触发

jobs:
  test:
    runs-on: ubuntu-latest  # 使用Ubuntu环境
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 拉取仓库代码

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # 指定Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytest  # 安装依赖

    - name: Run tests
      run: |
        pytest test_httpbin.py -v --junitxml=report.xml  # 运行测试

    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.xml  # 上传报告作为 artifact